
[tool.pixi.project]
name = "pram"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
PRAM = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.1.3,<3"
matplotlib = ">=3.9.2,<4"
jupyter = ">=1.1.1,<2"

[tool.pixi.feature.test.dependencies]
pytest = "*"
black = "*"

[tool.pixi.feature.test.tasks]
test = "pytest"
