
[tool.pixi.project]
name = "PRAM"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
PRAM = { path = ".", editable = true }
lets-plot=">=4.5.1,<5"
build=">=1.2.2.post1,<2"

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.1.3,<3"
matplotlib = ">=3.9.2,<4"
jupyter = ">=1.1.1,<2"
pandas = ">=2.2.3,<3"
plotnine = ">=0.14.1,<0.15"
shiny = ">=1.2.1,<2"

[tool.pixi.feature.test.dependencies]
pytest = "*"
black = "*"

[tool.pixi.feature.test.tasks]
test = "pytest"


